# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Continuous Integration
  jobs:
  - job: build_image
    steps: 
    - template: ../devops/templates/build.yaml
      parameters:
        acrServiceConnection: 'ACR'
        contextPath: 'adithya/app/ui'
        image_name: 'node-ui'
        buildContext: 'adithya/app/ui'
